package com.mprog.locationshare;

import androidx.annotation.NonNull;

import java.io.InvalidObjectException;

public class SerializableUserLocation {
    private String user;
    private float latitude;
    private float longitude;
    private long timeStamp;

    public SerializableUserLocation(String user, long timeStamp, float latitude, float longitude) {
        this.user = user;
        this.latitude = latitude;
        this.longitude = longitude;
        this.timeStamp = timeStamp;
    }

    public long getTimeStamp(){
        return timeStamp;
    }

    public float getLongitude() {
        return longitude;
    }

    public float getLatitude() {
        return latitude;
    }

    public String getUser() {
        return user;
    }

    /**
     * Get a string representation of the object that can be parsed.
     * @return parsable string containing the data of this instance.
     */
    @NonNull
    @Override
    public String toString() {
        return getUser()+ "," + getTimeStamp() + ","+getLatitude()+","+getLongitude();
    }

    /**
     * Get a SerializableUserLocation from a string.
     * @param s string representation of the object generated by the toString method.
     * @return A new SerializableUserLocation instance corresponding to the string.
     * @throws InvalidObjectException thrown if the string could not be correctly parsed.
     */
    public static SerializableUserLocation parse(String s) throws InvalidObjectException {
        String[] parts = s.split(",");

        if(parts.length != 4){
            throw new InvalidObjectException("Invalid string format " + s);
        }

        return new SerializableUserLocation(parts[0], Long.parseLong(parts[1]), Float.parseFloat(parts[2]), Float.parseFloat(parts[3]));
    }
}
